default:
	rm zad*.txt

z1:
	python3 validator.py zad1 python3 zad1.py 
	rm -f *.txt
z2:
	python3 validator.py zad2 python3 zad2.py 
	rm -f *.txt
z4:
	rm -f *.txt
	touch zad_input.txt
	python3 validator.py --stdio zad4 python3 sudoku.py 
	rm -f *.txt *.pl a.out
z5:
	rm -f *.txt
	touch zad_input.txt
	python3 validator.py zad5 python3 storms.py 
	rm -f *.txt *.pl a.out

