default:
	python3 zad1.py dodaj ksiazka hp jkr 2000
	python3 zad1.py dodaj osoba Jan Kowalski JK@gmail.com
	python3 zad1.py dodaj wypozyczenie Jan Kowalski JK@gmail.com hp jkr 2000
	python3 zad1.py wypisz
	python3 zad1.py dodaj zwrot Jan Kowalski JK@gmail.com hp jkr 2000
	python3 zad1.py wypisz
	python3 zad1.py dodaj wypozyczenie Jan Kowalski JK@gmail.com hp jkr 2000
	python3 zad1.py wypisz
	python3 zad1.py dodaj osoba Anna Dudek AD@gmail.com
	python3 zad1.py dodaj wypozyczenie Anna Dudek AD@gmail.com hp jkr 2000
	python3 zad1.py dodaj zwrot Jan Kowalski JK@gmail.com hp jkr 2000
	python3 zad1.py dodaj wypozyczenie Anna Dudek AD@gmail.com hp jkr 2000
	python3 zad1.py wypisz
	
clean:
	rm zad1.db