default:
	rm zad*.txt

z1:
	python3 validator.py zad1 python3 zad1.py 
z2:
	python3 validator.py zad2 python3 zad2.py 
z4:
	python3 validator.py zad4 python3 zad4.py 
z5:
	python3 validator.py zad5 python3 zad5.py 
